### ISSUE TITLE
Act 3 Architec

### ISSUE THREAD

**Issue by HECTOR-KDM02** [SistemasTecTlaxiaco/actividad-3-practica-architect-HECTOR-KDM02#1]
[practica architec 2-4.pdf](https://github.com/user-attachments/files/16841423/practica.architec.2-4.pdf)

Héctor Eduardo Santiago Bautista 

Actividad Architec

**Comment by josealfredo79** [comment]
Falta calificacion????

**Comment by josealfredo79** [comment]
Falta calificacion

**Comment by GibranVasquez** [comment]
20 cumple con todo

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
